### ISSUE TITLE
Please add tag or branch for WildFly `32.x` testing

### ISSUE THREAD

**Issue by scottmarlow** [wildfly/wildfly-tck-runners#157]
In preparation for the WildFly 32.0.1.Final release, please add a branch or tag for `32.x` to address the following failure:
> WILDFLY_BRANCH_NAME = 32.x
11:36:07 + git clone https://github.com/wildfly/wildfly-tck-runners
11:36:07 Cloning into 'wildfly-tck-runners'...
11:36:07 + cd wildfly-tck-runners/faces
11:36:07 + git checkout 32.x
11:36:07 error: pathspec '32.x' did not match any file(s) known to git

**Comment by jamezp** [comment]
Thank you @scottmarlow. Should be done now https://github.com/wildfly/wildfly-tck-runners/tree/32.x.
