### ISSUE TITLE
Save environment variables for authentication TCK to file.

### ISSUE THREAD

**Issue by darranl** [wildfly/wildfly-tck-runners#42]
If these are saved to file it will be easier to source them to manually run all or part of the old TCK,

**Comment by jamezp** [comment]
Maybe not what you're looking for, but this is one of the reasons I've setup some of the old TCK's in docker as it's easier to configure the environment.

**Comment by darranl** [comment]
In my case the issue is the old security-tck is not deploying the deployment before the test but the old authentication-tck is so the only real option is to run one test from each and see if I can compare why they are doing things differently.

As these scripts go through the complex steps to set it all up if I export the environment it will be easier to use the preparation from the scripts so in future debugging will be run the full script to prove it fails then use the output to be able to run tests individually to debug.
